app/features/orders/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, SelectField
from wtforms.validators import DataRequired
from datetime import date


class OrderForm(FlaskForm):
    state = SelectField('Estado', choices=[
                       ('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado')])
    delivery_date = DateField('Fecha de entrega',
                              validators=[DataRequired()], render_kw={"min": date.today().isoformat()})

app/features/orders/__init__.py
from .routes import orders_bp

app/features/orders/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from app.auth.role_authenticate import role_authenticate, current_user
from app.auth.roles import Roles
from app.features.products.model import Product
from app.features.orders.model import Order, OrderItem
from app.database import db
from app.features.orders.forms import OrderForm
from sqlalchemy import case

orders_bp = Blueprint('orders', __name__,
                      template_folder='templates', url_prefix='/orders/', static_folder='public')


@orders_bp.get('/')
@role_authenticate([Roles.ADMIN, Roles.CLIENTE])
def index():
    try:
        list = request.args.get("list", []).split(",")
        listAmount = request.args.get("amount", []).split(",")

        if not list:
            flash("No hay pedidos", 'error')
            return redirect(url_for('home.index'))

        list = [int(i) for i in list]

        print(list)
        listAmount = [int(i) for i in listAmount]
    except:
        flash("Error al procesar los pedidos", 'error')
        return redirect(url_for('home.index'))

    order_case = case(
        {id: index for index, id in enumerate(list)}, value=Product.id)

    listProducts = Product.query.filter(
        Product.id.in_(list)).order_by(order_case).all()

    listUnitTotal = []

    for product, amount in zip(listProducts, listAmount):
        listUnitTotal.append(product.price * amount)

    listOrders = zip(listProducts, listAmount, listUnitTotal)
    totalOrder = sum(listUnitTotal)

    context = {
        'orders': listOrders,
        'listOrders': list,
        'listAmount': listAmount,
        'totalOrder': totalOrder,
    }

    return render_template('order.jinja2', **context)


@orders_bp.get('/payment/')
@role_authenticate([Roles.CLIENTE, Roles.ADMIN])
def payment():
    try:
        list_ids = request.args.getlist("list")
        list_amount = request.args.getlist("amount")

        list_ids = [int(i) for i in list_ids]
        list_amount = [int(i) for i in list_amount]

        order_case = case(
            {id: index for index, id in enumerate(list_ids)}, value=Product.id)

        list_products: list[Product] = Product.query.filter(
            Product.id.in_(list_ids)).order_by(order_case).all()

        list_unit_total = []
        for product, amount in zip(list_products, list_amount):
            list_unit_total.append(product.price * amount)
            product.amount -= amount
        total_order = sum(list_unit_total)

        db.session.commit()

        order: Order = Order(current_user.id, 'pending', total_order)
        db.session.add(order)
        db.session.commit()

        for product, amount in zip(list_products, list_amount):
            order_item = OrderItem(order.id, product.id, amount, product.price)
            db.session.add(order_item)
            db.session.commit()
    except Exception as e:
        print(e)
        flash("Error al procesar los pedidos", 'error')
        return redirect(url_for('home.index'))

    list_orders = zip(list_products, list_amount, list_unit_total)

    session['list_orders'] = [
        {'product': {
            'id': product.id,
            'name': product.name,
        }, 'amount': amount, 'total': unit_total}
        for product, amount, unit_total in list_orders
    ]
    session['total_order'] = total_order

    return redirect(url_for('orders.payment_result'))


@orders_bp.get('/payment/success/')
@role_authenticate([Roles.CLIENTE, Roles.ADMIN])
def payment_result():
    list_orders = session.get('list_orders', [])
    total_order = session.get('total_order', 0)

    print(list_orders)

    if not list_orders or not total_order:
        flash("No se encontraron pedidos", 'error')
        return redirect(url_for('home.index'))

    session.pop('list_orders', None)
    session.pop('total_order', None)

    context = {
        'list_orders': list_orders,
        'total_order': total_order,
    }

    return render_template('payment.jinja2', **context)


@orders_bp.get('/all/')
@role_authenticate([Roles.ADMIN])
def all_orders():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 15, type=int)

    orders = Order.query.paginate(
        page=page, per_page=per_page, error_out=False)

    context = {
        'pagination': orders,
        'title': 'Todos los pedidos',
        'url_detail': 'orders.all_order',
        'url_pagination': 'orders.all_orders',
    }

    return render_template('list_orders.jinja2', **context)


@orders_bp.get('/all/<int:id>/')
@role_authenticate([Roles.ADMIN])
def all_order(id):
    order = Order.query.filter(Order.id == id).first()

    if order is None:
        flash("No se encontró el pedido", 'error')
        return redirect(url_for('orders.all_orders'))

    form: OrderForm = OrderForm()
    form.state.data = order.state
    form.delivery_date.data = order.delivery_date
    context = {
        'order': order,
        'form': form
    }

    return render_template('order_details.jinja2', **context)


@orders_bp.post('/all/<int:id>/')
@role_authenticate([Roles.ADMIN])
def all_order_post(id):
    order: Order = Order.query.filter(Order.id == id).first()

    if order is None:
        print("No se encontró el pedido")
        flash("No se encontró el pedido", 'error')
        return redirect(url_for('orders.all_orders'))

    print(order)

    form: OrderForm = OrderForm()

    if not form.validate_on_submit():
        context = {
            'order': order,
            'form': form
        }

        return render_template('order_details.jinja2', **context)

    order.delivery_date = form.delivery_date.data
    order.state = form.state.data
    db.session.commit()
    flash("Se ha actualizado el pedido", 'success')
    return redirect(url_for('orders.all_orders'))


@orders_bp.get('/user/')
@role_authenticate([Roles.CLIENTE, Roles.ADMIN])
def user_orders():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 15, type=int)

    orders = Order.query.filter(Order.user_id == current_user.id).paginate(
        page=page, per_page=per_page, error_out=False)
    context = {
        'pagination': orders,
        'title': 'Mis pedidos',
        'url_detail': 'orders.user_order',
        'url_pagination': 'orders.user_orders',
    }
    return render_template('list_orders.jinja2', **context)


@orders_bp.get('/user/<int:id>/')
@role_authenticate([Roles.CLIENTE, Roles.ADMIN])
def user_order(id):

    order = Order.query.filter(
        Order.id == id, Order.user_id == current_user.id).first()

    if order is None:
        flash("No se encontró el pedido", 'error')
        return redirect(url_for('orders.user_orders'))

    context = {
        'order': order,
    }

    return render_template('order_details.jinja2', **context)

app/features/orders/templates/list_orders.jinja2
{% extends "layout.jinja2" %}

{% block title %}
{{title}}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/paginate.css') }}">
{% endblock styles %}

{% block content %}
<main class="container-fluid p-3">

    <h1>
        {{title}}
    </h1>

    {% if not pagination.items %}
    <p>No hay pedidos</p>
    {% else %}
    <section class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Nombre del cliente</th>
                    <th>Cantidad de productos</th>
                    <th>Fecha de compra</th>
                    <th>Fecha de entrega</th>
                    <th>Estado</th>
                    <th>Total</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for order in pagination.items %}
                <tr>
                    <td>{{ order.user.username }}</td>
                    <td>{{ order.items|length }}</td>
                    <td>{{ order.creation_date.strftime("%d/%m/%Y %H:%M") }}</td>
                    <td>{{ order.delivery_date.strftime("%d/%m/%Y") }}</td>
                    <td>
                        {% if order.state == 'pending' %}
                        <span class="badge text-bg-warning">Pendiente</span>
                        {% elif order.state == 'sent' %}
                        <span class="badge text-bg-info">Enviado</span>
                        {% elif order.state == 'delivered' %}
                        <span class="badge text-bg-success">Entregado</span>
                        {% endif %}
                    </td>
                    <td>${{ order.total }}</td>
                    <td>
                        <a href="{{url_for(url_detail, id=order.id)}}">Ver detalles</a>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if pagination.pages > 1 %}
        <div class="d-flex justify-content-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% for page in pagination.iter_pages() %}
                    {% if page %}
                    <li class="page-item  {% if page == pagination.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for(url_pagination, page=page) }}">{{ page }}</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">...</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
        {% endif %}
    </section>

    {% endif %}

</main>
{% endblock content %}

app/features/orders/templates/order.jinja2
{% extends "layout.jinja2" %}

{% block title %}Página de Pedidos{% endblock %}

{% block content %}

<main class="container p-3">

    <h1>Pedidos</h1>

    <section class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Categoría</th>
                    <th>Precio Unitario</th>
                    <th>Cantidad</th>
                    <th>Total</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for product,amount,total in orders %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ amount }}</td>
                    <td>{{ total }}</td>
                    <td>
                        <button class="btn btn-sm btn-outline-danger btn-remove-order"
                            data-id_product="{{product.id}}">Quitar</button>
                        {% if amount > 1 %}
                        <button class="btn btn-sm btn-outline-secondary  btn-decrement-amount"
                            data-id_product="{{product.id}}">-</button>
                        {% endif %}

                        {% if amount < product.amount %} <button data-id_product="{{product.id}}"
                            class="btn btn-sm btn-outline-dark btn-increment-amount">
                            +
                            </button>
                            {% endif %}

                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4">Total</td>
                    <td>{{ totalOrder }}</td>
                    <td>
                        <a class="btn btn-outline-dark" id="pay-link"
                            href="{{ url_for('orders.payment', list=listOrders, amount=listAmount) }}">
                            Comprar
                            <span class="bi bi-cart-plus"> 🛒</span>
                        </a>
                    </td>
                </tr>

            </tfoot>
        </table>
    </section>
</main>


{% endblock content %}

{% block scripts %}
{{ super() }}

<script type="module" src="{{ url_for('orders.static', filename='js/showOrders.js') }}"></script>

{% endblock scripts %}

app/features/orders/templates/order_details.jinja2
{% extends "layout.jinja2" %}

{% block title %}Detalles del pedido{% endblock %}


{% block content %}
<main class="container-fluid p-3">

    <form class="col-12 col-md-8 col-lg-6  mx-auto row g-3  {{ 'was-validated' if form and form.errors }}"
        method="post">

        {% if current_user.role == Roles.ADMIN and form %}
        {{ form.csrf_token }}
        {% endif %}

        <h3>Detalles del pedido</h3>

        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <p class="col-form-label">Nombre del cliente:</p>
            </div>
            <div class="col-auto">
                <input class="form-control-plaintext" disabled readonly value="{{ order.user.username }}" />
            </div>
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <p class="col-form-label">Cantidad de productos:</p>
            </div>
            <div class="col-auto">
                <input class="form-control-plaintext" disabled readonly value="{{ order.items|length }}" />
            </div>
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <p class="col-form-label">Fecha de compra:</p>
            </div>
            <div class="col-auto">
                <input class="form-control-plaintext" disabled readonly
                    value='{{ order.creation_date.strftime("%d/%m/%Y %H:%M") }}' />
            </div>
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <p class="col-form-label">Fecha de entrega:</p>
            </div>
            <div class="col-auto">
                {% if current_user.role == Roles.ADMIN and form %}
                {{ form and form.delivery_date(class="form-control") }}
                {% else %}
                <input class="form-control-plaintext" disabled readonly
                    value='{{ order.delivery_date.strftime("%d/%m/%Y") }}' />
                {% endif %}
            </div>
        </div>

        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <p class="col-form-label"> Estado:</p>
            </div>
            <div class="col-auto">
                {% if current_user.role == Roles.ADMIN and form %}
                {{ form.state(class="form-control") }}
                {% elif order.state == 'pending' %}
                <span class="badge text-bg-warning">Pendiente</span>
                {% elif order.state == 'sent' %}
                <span class="badge text-bg-info">Enviado</span>
                {% elif order.state == 'delivered' %}
                <span class="badge text-bg-success">Entregado</span>
                {% endif %}
            </div>
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <p class="col-form-label">Total:</p>
            </div>
            <div class="col-auto">
                ${{ order.total }}
            </div>
        </div>


        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Cantidad</th>
                        <th>Precio Unitario</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order.items %}
                    <tr>
                        <td>{{ item.product.name and item.product.name or 'No disponible' }}</td>
                        <td>{{ item.amount }}</td>
                        <td>${{ item.price }}</td>
                        <td>${{ item.amount * item.price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            {% if current_user.role == Roles.ADMIN and form %}
            <a class="btn btn-outline-dark" href="{{ url_for('orders.all_orders') }}">Volver</a>
            <button class="btn btn-dark" type="submit">Enviar</button>
            {% elif current_user.role == Roles.ADMIN %}
            <a class="btn btn-outline-dark" href="{{ url_for('orders.user_orders') }}">Volver</a>
            <a href="{{ url_for('orders.all_order', id=order.id) }}" class="btn btn-outline-dark">Editar</a>
            {% else %}
            <a class="btn btn-outline-dark" href="{{ url_for('orders.user_orders') }}">Volver</a>
            {% endif %}
        </div>
    </form>
</main>
{% endblock content %}

app/features/orders/templates/payment.jinja2
{% extends "layout.jinja2" %}

{% block title %}Pago{% endblock %}

{% block content %}

<main class="container p-3">
    <h2>Pedido con éxito</h2>
    <p class="fs-4">Se ha realizado el pedido con éxito</p>

    <p class="fs-4">El pago fue de <span class="fw-bold">${{ total_order }} </span></p>

    <a class="btn btn-outline-dark mb-3" href="{{ url_for('home.index') }}">Volver</a>
    <p class="fs-4 fw-bold">Lista de pedidos</p>
    <ul class="list-group">
        {% for item in list_orders %}
        <li class="list-group-item">
            Producto: {{ item.product.name }}
            <br>
            Cantidad: {{ item.amount }}
            <br>
            Total: <span class="fw-bold">${{ item.total }}</span>
        </li>
        {% endfor %}
    </ul>
</main>

{% endblock content %}

{% block scripts %}
{{ super() }}

<script type="module"></script>

{% endblock scripts %}