app/features/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, FloatField, IntegerField, TextAreaField, SelectField
from wtforms.validators import DataRequired


class FormProduct(FlaskForm):
    name = StringField('Nombre', validators=[DataRequired()])
    description = TextAreaField('Descripción', validators=[DataRequired()])
    price = FloatField('Precio', validators=[DataRequired()])
    amount = IntegerField('Cantidad', validators=[DataRequired()])
    category = SelectField('Categoría',
                           validators=[DataRequired()],
                           choices=[('electrónicos', 'Electrónicos'),
                                    ('ropa', 'Ropa'),
                                    ('comida', 'Comida'),
                                    ('juguetes', 'Juguetes'),
                                    ('deportes', 'Deportes'),
                                    ('libros', 'Libros'),
                                    ('música', 'Música'),
                                    ('computadoras', 'Computadoras'),
                                    ('videojuego', 'Videojuego'),
                                    ('otros', 'Otros'),
                                    ]
                           )

app/features/products/__init__.py
from .routes import products_bp

app/features/products/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.auth.role_authenticate import role_authenticate
from app.auth.roles import Roles
from app.features.products.forms import FormProduct
from app.features.products.model import Product
from app.database import db


products_bp = Blueprint('products', __name__, template_folder='templates')


@products_bp.get('/products/')
@role_authenticate([Roles.ADMIN])
def index():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 15, type=int)

    print(page, per_page,)

    products = Product.query.paginate(
        page=page, per_page=per_page, error_out=False)

    context = {
        'pagination': products
    }

    return render_template('products.jinja2', **context)


@products_bp.get('/products/create/')
@role_authenticate([Roles.ADMIN])
def create():
    context = {
        'form': FormProduct(),
        'title': 'Crear Producto',
        'btn_text': 'Crear',
    }
    return render_template('form_product.jinja2', **context)


@products_bp.post('/products/create/')
@role_authenticate([Roles.ADMIN])
def create_product():

    form: FormProduct = FormProduct()
    context = {
        'form': form,
        'title': 'Crear Producto',
        'btn_text': 'Crear',
    }

    if not form.validate_on_submit():
        print(form.errors)
        return render_template('form_product.jinja2', **context)

    try:
        product = Product(form.name.data, form.description.data,
                          form.price.data, form.amount.data, form.category.data)

        db.session.add(product)
        db.session.commit()

        return redirect(url_for('products.index'))
    except Exception as e:
        flash("Error al crear el producto", 'error')
        print(e)
        return redirect(url_for('products.create'))


@products_bp.get('/products/<int:id>/edit/')
@role_authenticate([Roles.ADMIN])
def edit(id):
    product = Product.query.get(id)
    form: FormProduct = FormProduct()

    if not product:
        flash("Producto no encontrado", 'error')
        return redirect(url_for('products.index'))

    form.name.data = product.name
    form.description.data = product.description
    form.price.data = product.price
    form.amount.data = product.amount
    form.category.data = product.category

    context = {
        'form': form,
        'title': 'Editar Producto',
        'btn_text': 'Editar',
    }
    return render_template('form_product.jinja2', **context)


@products_bp.post('/products/<int:id>/edit/')
@role_authenticate([Roles.ADMIN])
def edit_product(id):

    form: FormProduct = FormProduct()
    context = {
        'form': form,
        'title': 'Editar Producto',
        'btn_text': 'Editar',
    }

    if not form.validate_on_submit():
        print(form.errors)
        return render_template('form_product.jinja2', **context)

    try:
        product: Product = Product.query.get(id)
        product.name = form.name.data
        product.description = form.description.data
        product.price = form.price.data
        product.amount = form.amount.data
        product.category = form.category.data

        db.session.commit()
        return redirect(url_for('products.index'))
    except Exception as e:
        flash("Error al editar el producto", 'error')
        print(e)
        return redirect(url_for('products.edit', id=id))


@products_bp.get('/products/<int:id>/delete/')
@role_authenticate([Roles.ADMIN])
def delete(id):
    product = Product.query.get(id)
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('products.index'))

app/features/products/templates/create_product.jinja2
{% extends "layout.jinja2" %}

{% block title %}Crear Producto{% endblock %}

{% block content %}
<form method="post">
  {{ form.csrf_token }}
  {{form.name.label}}
  {{form.name}}
  {{form.description.label}}
  {{form.description}}
  {{form.price.label}}
  {{form.price(min=0.00)}}
  {{form.amount.label}}
  {{form.amount(min=0)}}
  {{form.category.label}}
  {{form.category}}
  <input type="submit" value="Crear">

</form>
{% endblock content %}

app/features/products/templates/form_product.jinja2
{% extends "layout.jinja2" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<main class="container-fluid p-3">
    <form class="col-12 col-md-8 col-lg-6  mx-auto row g-3  {{ 'was-validated' if form.errors }}" method="post">
        <h3>{{title}}</h3>
        {{ form.csrf_token }}
        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.price.label(class="form-label") }}
            {{ form.price(class="form-control",price=0.00) }}
        </div>
        <div class="mb-3 col-md-6">
            {{ form.amount.label(class="form-label") }}
            {{ form.amount(class="form-control",min=0) }}
        </div>
        <div class="mb-3 col-md-6">
            {{ form.category.label(class="form-label") }}
            {{ form.category(class="form-control") }}
        </div>
        <div>
            <button class="btn btn-outline-dark" type="reset">Limpiar</button>
            <button class="btn btn-dark" type="submit">{{btn_text}}</button>
        </div>
    </form>
</main>
{% endblock content %}

app/features/products/templates/products.jinja2
{% extends "layout.jinja2" %}

{% block title %}Página de Productos{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/paginate.css') }}">
{% endblock styles %}

{% block content %}
<main class="container-fluid p-3">
    <h1>Productos</h1>
    <section class="d-flex justify-content-end mb-3">
        <a class="btn btn-outline-dark" href="{{ url_for('products.create') }}">Agregar Producto</a>
    </section>

    <section class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Categoría</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for product in pagination.items %}
                <tr>
                    <td>{{ product.name }}</td>
                    {# Descripción reduce a 10 caracteres #}
                    <td>{{ product.description | truncate(70) }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.amount }}</td>
                    <td>{{ product.category }}</td>
                    <td>
                        <a class="btn btn-sm btn-outline-dark"
                            href="{{ url_for('products.edit', id=product.id) }}">Editar</a>
                        <a class="btn btn-sm btn-outline-danger"
                            href="{{ url_for('products.delete', id=product.id) }}">Borrar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if pagination.pages > 1 %}
        <div class="d-flex justify-content-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">

                    {% for page in pagination.iter_pages() %}
                    <li class="page-item  {% if page == pagination.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('products.index', page=page) }}">{{ page }}</a>
                    </li>
                    {% endfor %}

                </ul>
            </nav>
        </div>
        {% endif %}
    </section>
</main>

{% endblock %}