app/features/home/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.auth.role_authenticate import role_authenticate
from app.features.products.model import Product

home_bp = Blueprint(
    'home', __name__, template_folder='templates', static_folder='public'
)


@home_bp.get('/')
def index():
    context = {
        'products': Product.query.all()
    }
    return render_template('index.jinja2', **context)


@home_bp.get('/category/<path:path>/')
def product_category(path):

    if path not in ['electrónicos', 'ropa', 'comida', 'juguetes', 'deportes', 'libros', 'música', 'computadoras',
                    'videojuego', 'otros']:
        flash("Categoría no encontrada", 'error')
        return redirect(url_for('home.index'))

    context = {
        'products': Product.query.filter(Product.category.like(path)).all(),
        'category': path
    }

    return render_template('index.jinja2', **context)

app/templates/error.jinja2
{% extends "layout.jinja2" %}

{% block title %}Error{% endblock %}

{% block content %}
<h1>Error</h1>
<p>Ocurrió un error, por favor intente nuevamente.</p>
{% endblock %}

app/templates/layout.jinja2
<!DOCTYPE html>
<html lang="es_MX">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Online Store
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">

    {% block styles %}


    {% endblock styles %}

</head>


<body>
    <header>
        <nav class="navbar navbar-expand-xxl bg-body-tertiary">
            <div class="container-fluid ">
                <a class="navbar-brand" href="{{ url_for('home.index') }}">Tienda Online</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a href="{{ url_for('home.index') }}"
                                class="nav-link {% if request.path == url_for('home.index') %}active{% endif %}">
                                Todos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('home.product_category', path='electrónicos') }}"
                                class="nav-link {% if request.path == '/category/electrónicos/' %}active{% endif %}">
                                Electrónicos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/ropa/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='ropa') }}">Ropa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/comida/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='comida') }}">
                                Comida
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/juguetes/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='juguetes') }}">
                                Juguetes
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/deportes/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='deportes') }}">
                                Deportes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/libros/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='libros') }}">
                                Libros
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/música/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='música') }}">
                                Música
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/computadoras/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='computadoras') }}">
                                Computadoras
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/videojuego/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='videojuego') }}">
                                Videojuego
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/category/otros/' %}active{% endif %}"
                                href="{{ url_for('home.product_category', path='otros') }}">
                                Otros
                            </a>
                        </li>

                        {% if current_user.is_authenticated %}
                        {% if current_user.role == Roles.ADMIN %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path.startswith('/products/') %}active{% endif %}"
                                href="{{ url_for('products.index') }}">
                                Productos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path.startswith('/orders/all/') %}active{% endif %}"
                                href="{{ url_for('orders.all_orders') }}">
                                Todos los pedidos
                            </a>

                        </li>
                        {% endif %}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle
                            {% if request.path == '/user/' or request.path == '/orders/user/'%}active{% endif %}"
                                href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Usuario: {{current_user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ url_for('auth.get_user') }}">Datos</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('orders.user_orders') }}">Mis pedidos</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item text-danger" href="{{ url_for('auth.logout') }}">
                                        Cerrar Sesión
                                    </a>
                                </li>
                            </ul>
                        </li>


                        {% else %}
                        <li class="nav-item align-self-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-primary" href="{{ url_for('auth.login') }}">Iniciar
                                    Sesión</a>
                                <a class="btn btn-sm btn-outline-primary"
                                    href="{{ url_for('auth.register') }}">Registro</a>
                            </div>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}

</body>
{% block scripts %}
<script src="{{ url_for('static', filename='bootstrap/js/popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>

{% endblock scripts %}

</html>